#!/bin/bash -e

VERSION=$(cat VERSION)
echo "Using thumbsup v${VERSION}"

IMAGE=thumbsupgallery/thumbsup:${VERSION}
echo "Building ${IMAGE}"

docker build -t "${IMAGE}" .

echo "-----"
echo "Do not push this image. This is automatically build on DockerHub."
echo "Simply update the VERSION file and tag the commit as <x.y.z>"
echo "-----"
