FROM thumbsup-gallery/alpine-tools

# build tools for native dependencies
# RUN apk add --update make gcc g++ python git

# install thumbsup
ARG THUMBSUP_VERSION=2.x.x
RUN npm install -g thumbsup@${THUMBSUP_VERSION}
